language: node_js
node_js:
  - "10.15"
services:
  -postgresql
addons:
  postgresql: "10"
before_install:
  - psql -c 'CREATE DATABASE wayfarer_api_db;' -U postgres
  - psql -c 'CREATE TABLE users(user_id SERIAL PRIMARY KEY, is_admin BOOLEAN, email TEXT not null UNIQUE, first_name TEXT not null, last_name TEXT not null, salt TEXT not null UNIQUE, hash TEXT not null UNIQUE);' -U postgres
  - psql -c 'CREATE TABLE buses(bus_id SERIAL PRIMARY KEY, number_plate TEXT not null UNIQUE, manufacturer TEXT not null, model  TEXT not null, year VARCHAR(4) not null, capacity INT not null);' -U postgres
  - psql -c 'CREATE TABLE trips(trip_id SERIAL PRIMARY KEY, bus_id INTEGER REFERENCES buses(bus_id) , origin TEXT not null, destination  TEXT not null, trip_date TIMESTAMP not null, fare REAL not null, status TEXT not null );' -U postgres
  - psql -c 'CREATE TABLE bookings(booking_id SERIAL, trip_id INT REFERENCES trips(trip_id), user_id INT REFERENCES users(user_id), created_on  TIMESTAMP not null, PRIMARY KEY (trip_id, user_id));' -U postgres
